const data = {
  products: [
    {
      name: "Women Shoes",
      slug: "nike-shoes",
      category: "shoes",
      image: "./images/P1.jpg",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      desription: "high quality",
    },
    {
      name: "Running Shoes",
      slug: "puma-shoes",
      category: "shoes",
      image: "./images/P2.jpg",
      price: 90,
      countInStock: 20,
      brand: "puma",
      rating: 4.5,
      numReviews: 10,
      desription: "high quality",
    },
    {
      name: "Sneakers",
      slug: "converse-shoes",
      category: "shoes",
      image: "./images/P3.jpg",
      price: 150,
      countInStock: 10,
      brand: "converse",
      rating: 3.5,
      numReviews: 10,
      desription: "high quality",
    },
    {
      name: "Men Shoes",
      slug: "adidas-shoes",
      category: "shoes",
      image: "./images/P4.jpg",
      price: 110,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      desription: "high quality",
    },
  ],
};
export default data;
